### ISSUE TITLE
Error: No value present in BloodRequest

### ISSUE THREAD

**Issue by Code-4ge** [taha-yasin/blood-donor-backend#16]
While creating blood request two or more times from same user, getting a **_No Value Present Error_**.

```
INFO 1724 --- [nio-8080-exec-6] i.t.b.service.BloodRequestService        : Attempting to create blood request
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:143)
	at io.tahayasin.blood_donor.service.BloodRequestService.request(BloodRequestService.java:153)
	at io.tahayasin.blood_donor.service.BloodRequestService$$FastClassBySpringCGLIB$$5c4d400e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	.
	.
	.
	.
WARN 1724 --- [nio-8080-exec-8] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [java.util.NoSuchElementException: No value present]
```

**Comment by taha-yasin** [comment]
This is because entity unitRequired is initialized to null as the actual entity should be unitsRequired.
#15 will also solve this issue.
